### ISSUE TITLE
Unable to build with the latest `ide-flatpak-wrapper`

### ISSUE THREAD

**Issue by czhang03** [flathub/com.vscodium.codium#377]
Hi, I was trying to test my changes to enable linuxbrew (https://github.com/czhang03/ide-flatpak-wrapper/commit/a2294f2974c28bfa0344cf00a748d412bb1a5c3c). However I noticed that vscodium doesn't seem to build with the latest commit of ide-flatpak-wrapper.

Here is a sample of my yaml file:
```yaml
    sources:
      - type: git
        url: https://github.com/flathub-infra/ide-flatpak-wrapper.git
        commit: 3314b55ccd4ece8810715787e246f8407e20caab
      - type: file
        path: README.md
      - type: file
        path: sdk_update.md
```
The command I ran:
```
flatpak-builder --force-clean --install-deps-from=flathub --user --repo=repo --install build/ com.vscodium.codium.yaml
```
and here is the sample of the log:
```
HEAD is now at 3314b55 ci: Remove triggering branch restriction
The Meson build system
Version: 1.5.2
Source dir: /run/build/wrapper-flatpak-wrapper
Build dir: /run/build/wrapper-flatpak-wrapper/_flatpak_build
Build type: native build

../meson.build:1:0: ERROR: Unknown options: "envs, envs_inner, zypak, zypak_args"

A full log can be found at /run/build/wrapper-flatpak-wrapper/_flatpak_build/meson-logs/meson-log.txt
Error: module wrapper-flatpak-wrapper: Child process exited with code 1
```

I don't know if people are aware of this issue, or should I report this at ide-flatpak-wrapper?
