### ISSUE TITLE
Help needed with creating a sdk extension

### ISSUE THREAD

**Issue by UnpaidBonsai** [flathub/com.vscodium.codium#419]
Hi. I hope this is not totally out of place here. I found no better place to ask this kind of question (maybe the flatpak repo for com.visualstudio.code). I do not know of any chat room or special forum for this question or a better blog post describing exactly how to create a flatpak vscodium sdk extension.

I want to make [this program](https://github.com/NixOS/nixfmt) available inside vscodium, as [this vsix extension](https://open-vsx.org/extension/jnoortheen/nix-ide) uses it for formatting. (not sure if that is the best way to use this extension as it also supports an lsp - maybe I should try to make this available but thats another topic I guess.)

I got inspiration from the Extensions `org.freedesktop.Sdk.Extension.golang`, `org.freedesktop.Sdk.Extension.node20` and from [this blog entry](https://www.cogitri.dev/posts/06-using-flatpaked-vscode/).
I have got so far as to add the file as a module like [described here](https://docs.flatpak.org/en/latest/module-sources.html#file-sources) and set the right permissions for execution with `install`.

```yaml
id: org.freedesktop.Sdk.Extension.nixfmt
branch: '24.08'
runtime: org.freedesktop.Sdk
runtime-version: '24.08'
sdk: org.freedesktop.Sdk
build-extension: true
separate-locales: false
modules:
  - name: nixfmt
    buildsystem: simple
    sources:
      - type: filengt5nb
        dest-filename: nixfmt
        url: https://github.com/NixOS/nixfmt/releases/download/v0.6.0/nixfmt-x86_64-linux
        sha256: 8b07a02858af8de48c5ab2830cc61ce6b63d0f9a5539f8ad55b16a6e3e7509d5
    build-commands:
      - install -Dm755 nixfmt /usr/lib/sdk/nixfmt/nixfmt
  - name: scripts
    buildsystem: simple
    build-commands:
      - cp enable.sh /usr/lib/sdk/nixfmt/
    sources:
      - type: script
        dest-filename: enable.sh
        commands:
          - export PATH=$PATH:/usr/lib/sdk/nixfmt
```

I create the sdk extension with `flatpak-builder --user --install --force-clean app org.freedesktop.Sdk.Extension.nixfmt.yaml`.

```
$ flatpak list --user
Name           Application ID                              Version        Branch        Origin
nixfmt         org.freedesktop.Sdk.Extension.nixfmt                       24.08         nixfmt-origin
```

And when I run `flatpak-builder --run app/ org.freedesktop.Sdk.Extension.nixfmt.yaml bash` the folders `/usr/lib/sdk/{golang,nix,nixfmt,openjdk,rust-stable,ziglang}` exist. Inside `usr/lib/sdk/nixfmt` all three files exist:

```
bash-5.2$ ls /usr/lib/sdk/nixfmt/ -l
total 5400
-rwxr-xr-x. 1 myusername myusername      48 Jan  1  1970 enable.sh
-rw-r--r--. 1 myusername myusername    1326 Jan  1  1970 manifest.json
-rwxr-xr-x. 1 myusername myusername 5519160 Jan  1  1970 nixfmt
```

When starting vscodium from the commandline having the overwrite `FLATPAK_ENABLE_SDK_EXT=golang,ziglang,openjdk,rust-stable,nixfmt` the `enable.sh` scripts run. So with my current config seems to work because the output looks like this:

```
$ flatpak run com.vscodium.vscodium
codium-wrapper: Evaluating /usr/lib/sdk/golang/enable.sh
codium-wrapper: Evaluating /usr/lib/sdk/ziglang/enable.sh
codium-wrapper: Evaluating /usr/lib/sdk/openjdk/enable.sh
codium-wrapper: Evaluating /usr/lib/sdk/rust-stable/enable.sh
codium-wrapper: Evaluating /usr/lib/sdk/nixfmt/enable.sh
codium-wrapper: Setting up NPM packages
codium-wrapper: Setting up Cargo packages
codium-wrapper: Setting up Python packages
codium-wrapper: Setting up Ruby packages
Warning: 'enable-wayland-ime' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'enable-features' is not in the list of known options, but still passed to Electron/Chromium.
```

(if I did not install the extension but specified its name inside `FLATPAK_ENABLE_SDK_EXT` I get this output: `codium-wrapper: Requested SDK extension "nixfmt" is not installed`)

But when I check `/usr/lib/sdk/nixfmt` inside of the vscodium console the folder does not exist but `/usr/lib/sdk/{golang,openjdk,rust-stable,ziglang}` do.

thanks for any kind of help :)
